[package]
name = "component"
version = "0.1.0"
edition = "2021"

[package.metadata.component]
package = "rust:component"

[lib]
crate-type = ["cdylib"]
path = "src/rust/lib.rs"

[dependencies]
wit-bindgen = "0.27"
